apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    context: "pr"
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  postsubmits:
  # Run release on push to main/master
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
  # Run release on version tag push (e.g. v0.1.2, v1.0.0)
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - ^v[0-9]+\.[0-9]+\.[0-9]+$
