apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    context: "pr"
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  postsubmits:
  # Run release only on push to main/master (one run per push; no tag trigger to avoid multiple runs)
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
